# -*- coding: utf-8 -*-
"""2106091_NisaN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwSjx4GTWg_ihYDtDgYp_ZHYA7bMSUvp
"""

from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

# Mengunggah citra dari komputer Anda
from google.colab import files
uploaded = files.upload()

# Memeriksa citra yang diunggah
for filename in uploaded.keys():
    img = Image.open(filename)
    grayscale_img = img.convert('L')  # Mengonversi citra ke grayscale
    rgb_img = img.convert('RGB')  # Mengonversi citra ke mode RGB
    r, g, b = rgb_img.split()  # Membagi citra menjadi komponen R, G, dan B

    # Menampilkan citra asli
    plt.figure(figsize=(15, 5))
    plt.subplot(151)
    plt.title("Citra Asli")
    plt.imshow(img)
    plt.axis('off')

    # Menampilkan komponen Red (R)
    plt.subplot(152)
    plt.title("Komponen Red (R)")
    plt.imshow(np.array(r), cmap='Reds')
    plt.axis('off')

    # Menampilkan komponen Green (G)
    plt.subplot(153)
    plt.title("Komponen Green (G)")
    plt.imshow(np.array(g), cmap='Greens')
    plt.axis('off')

    # Menampilkan komponen Blue (B)
    plt.subplot(154)
    plt.title("Komponen Blue (B)")
    plt.imshow(np.array(b), cmap='Blues')
    plt.axis('off')

    # Menampilkan citra grayscale (0-255)
    plt.subplot(155)
    plt.title("Citra Grayscale (0-255)")
    plt.imshow(grayscale_img, cmap='gray', vmin=0, vmax=255)
    plt.axis('off')

    plt.show()

    # Simpan citra grayscale
    grayscale_img.save('grayscale_' + filename)
    print('Citra Grayscale telah disimpan sebagai grayscale_' + filename)

from PIL import Image

# Mengunggah citra dari komputer Anda
from google.colab import files
uploaded = files.upload()

# Memeriksa citra yang diunggah
for filename in uploaded.keys():
    img = Image.open(filename)
    grayscale_img = img.convert('L')  # Mengonversi citra ke grayscale

    # Simpan citra dalam format PGM
    pgm_filename = 'grayscale_' + filename.split('.')[0] + '.pgm'
    grayscale_img.save(pgm_filename)

    print('Citra Grayscale telah disimpan sebagai', pgm_filename)